### ISSUE TITLE
krunner-vscodeprojects is outdated

### ISSUE THREAD

**Issue by irgendwr** [sergeyshevch/AUR#2]
The current version of krunner-vscodeprojects is 1.2.0: https://github.com/alex1701c/krunner-vscodeprojects/releases/tag/1.2.0

**Comment by sergeyshevch** [comment]
Hello @irgendwr. Thanks for your PR. For now, I'm not using Arch on my machines. I will try to found some Linux machine to publish it today.

**Comment by sergeyshevch** [comment]
If you want to maintain it I can transfer repo and package to you

**Comment by irgendwr** [comment]
> If you want to maintain it I can transfer repo and package to you

Sure, that would be fine for me

**Comment by sergeyshevch** [comment]
@irgendwr Can you please write me by email then sergeyshevchdevelop@gmail.com. I didn't find how to transfer the AUR package but I can add you as a Contributor and transfer Github repo
